import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../components/aboutMe'
import Navigation from '../components/navigation'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Melroy Glan Pinto</title>
        <meta name="description" content="Generated by Melroy Glan Pinto" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <AboutMe />
    </>
  )
}

export default Home
